<?php
// Determine the base path based on current directory depth
$current_path = $_SERVER['PHP_SELF'];
$base_path = './';
if (strpos($current_path, '/vulnerabilities/') !== false) {
    $parts = explode('/vulnerabilities/', $current_path);
    if (isset($parts[1]) && strpos($parts[1], '/') !== false) {
        $base_path = '../../';
    } else {
        $base_path = '../';
    }
} elseif (strpos($current_path, '/tools/') !== false || strpos($current_path, '/compare/') !== false || strpos($current_path, '/components/') !== false) {
    $base_path = '../';
}


// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit7e93b1a048e1bccecc4b8b3d0e7c898a
{
    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'Firebase\\JWT\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Firebase\\JWT\' => 
        array (
            0 => __DIR__ . '/..' . '/firebase/php-jwt/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit7e93b1a048e1bccecc4b8b3d0e7c898a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit7e93b1a048e1bccecc4b8b3d0e7c898a::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit7e93b1a048e1bccecc4b8b3d0e7c898a::$classMap;

        }, null, ClassLoader::class);
    }
}
